### ISSUE TITLE
ValueError: Namespace Gtk not available

### ISSUE THREAD

**Issue by peterjc** [conda-forge/pygobject-feedstock#20]
Testing pygobject on macOS, ran into the following.

```
$ conda install pygobject
...
$ python -c "import gi; gi.require_version('Gtk', '3.0')"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/xxx/miniconda3/lib/python3.7/site-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Gtk not available
```

Looks like https://gitlab.gnome.org/GNOME/pygobject/issues/329 which suggests a missing environment variable? Or missing dependency?

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/xxx/miniconda3:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
appdirs                   1.4.3                    pypi_0    pypi
asn1crypto                1.0.1                    py37_0  
aspy-refactor-imports     1.1.0                    pypi_0    pypi
astor                     0.8.1                    pypi_0    pypi
attrs                     19.3.0                     py_0  
babel                     2.8.0                    pypi_0    pypi
bandit                    1.6.2                    pypi_0    pypi
biopython                 1.77.dev0                pypi_0    pypi
black                     19.10b0                  pypi_0    pypi
bleach                    3.1.0                    pypi_0    pypi
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cached-property           1.5.1                    pypi_0    pypi
cairo                     1.16.0            he1c11cd_1002    conda-forge
cairocffi                 1.1.0                    pypi_0    pypi
certifi                   2019.11.28               py37_0    conda-forge
cffi                      1.12.3           py37hb5b8e2f_0  
chardet                   3.0.4                 py37_1003  
click                     7.0                      pypi_0    pypi
conda                     4.8.2                    py37_0    conda-forge
conda-package-handling    1.6.0            py37h1de35cc_0  
cryptography              2.7              py37ha12b0ac_0  
cutadapt                  2.8              py37h01d97ff_0    bioconda
cycler                    0.10.0                   pypi_0    pypi
deap                      1.3.1                    pypi_0    pypi
decorator                 4.4.0                    pypi_0    pypi
dnaio                     0.4.1            py37h01d97ff_0    bioconda
docutils                  0.15.2                   pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
filelock                  3.0.12                   pypi_0    pypi
flake8                    3.7.9                    pypi_0    pypi
flake8-black              0.1.1                    pypi_0    pypi
flake8-bugbear            20.1.3                   pypi_0    pypi
flake8-docstrings         1.5.0                    pypi_0    pypi
flake8-import-order       0.18.1                   pypi_0    pypi
flake8-polyfill           1.0.2                    pypi_0    pypi
flynt                     0.40.1                   pypi_0    pypi
fontconfig                2.13.1            h6b1039f_1001    conda-forge
freetype                  2.10.0               h24853df_1    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
gitdb2                    2.0.6                    pypi_0    pypi
gitpython                 3.0.5                    pypi_0    pypi
glib                      2.58.3            h9d45998_1002    conda-forge
gobject-introspection     1.58.2          py37h93883a9_1002    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
idna                      2.8                      py37_0  
imagesize                 1.2.0                    pypi_0    pypi
importlib-metadata        0.23                     pypi_0    pypi
isort                     4.3.21                   pypi_0    pypi
jinja2                    2.10.3                   pypi_0    pypi
kiwisolver                1.1.0                    pypi_0    pypi
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libiconv                  1.15              h01d97ff_1005    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
libxml2                   2.9.10               h53d96d6_0    conda-forge
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                2.2.2                    pypi_0    pypi
mccabe                    0.6.1                    pypi_0    pypi
mock                      4.0.1                    pypi_0    pypi
more-itertools            7.2.0                    pypi_0    pypi
ncbi-acc-download         0.2.5                    pypi_0    pypi
ncurses                   6.1                  h0a44026_1  
networkx                  2.4                      pypi_0    pypi
numpy                     1.17.3                   pypi_0    pypi
openssl                   1.1.1d               h0b31af3_0    conda-forge
packaging                 19.2                     pypi_0    pypi
pandas                    0.25.3                   pypi_0    pypi
pathspec                  0.6.0                    pypi_0    pypi
pbr                       5.4.4                    pypi_0    pypi
pcre                      8.43                 h0a44026_0  
pigz                      2.3.4                         0    conda-forge
pillow                    7.0.0                    pypi_0    pypi
pip                       19.2.3                   py37_0  
pixman                    0.38.0            h01d97ff_1003    conda-forge
pkginfo                   1.5.0.1                  pypi_0    pypi
pluggy                    0.13.0                   pypi_0    pypi
py                        1.8.0                    pypi_0    pypi
pycairo                   1.19.1           py37h83b1bec_0    conda-forge
pycodestyle               2.5.0                    pypi_0    pypi
pycosat                   0.6.3            py37h1de35cc_0  
pycparser                 2.19                     py37_0  
pydocstyle                5.0.2                    pypi_0    pypi
pydot                     1.4.1                    pypi_0    pypi
pyflakes                  2.1.1                    pypi_0    pypi
pygments                  2.4.2                    pypi_0    pypi
pygobject                 3.30.5                   pypi_0    pypi
pyopenssl                 19.0.0                   py37_0  
pyparsing                 2.4.2                    pypi_0    pypi
pyro4                     4.79                     pypi_0    pypi
pysocks                   1.7.1                    py37_0  
pytest                    5.3.5                    pypi_0    pypi
python                    3.7.4                h359304d_1  
python-dateutil           2.8.0                    pypi_0    pypi
python-git                2018.2.1                 pypi_0    pypi
python-levenshtein        0.12.0                   pypi_0    pypi
python.app                2                        py37_9  
pytz                      2019.3                   pypi_0    pypi
pyxrd                     0.8.2                    pypi_0    pypi
pyyaml                    5.3                      pypi_0    pypi
readline                  7.0                  h1de35cc_5  
readme-renderer           24.0                     pypi_0    pypi
regex                     2019.8.19                pypi_0    pypi
reorder-python-imports    1.9.0                     dev_0    <develop>
reportlab                 3.5.32                   pypi_0    pypi
requests                  2.22.0                   py37_0  
requests-toolbelt         0.9.1                    pypi_0    pypi
restructuredtext-lint     1.3.0                    pypi_0    pypi
ruamel_yaml               0.15.46          py37h1de35cc_0  
scipy                     1.4.1                    pypi_0    pypi
send2trash                1.5.0                    pypi_0    pypi
serpent                   1.30.2                   pypi_0    pypi
setuptools                41.4.0                   py37_0  
six                       1.12.0                   py37_0  
smmap2                    2.0.5                    pypi_0    pypi
snowballstemmer           2.0.0                    pypi_0    pypi
sphinx                    2.3.1                    pypi_0    pypi
sphinx-rtd-theme          0.4.3                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.1                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.1                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.2                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.2                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.3                    pypi_0    pypi
sqlalchemy                1.3.10                   pypi_0    pypi
sqlite                    3.30.0               ha441bb4_0  
stevedore                 1.31.0                   pypi_0    pypi
thapbi-pict               0.6.9                     dev_0    <develop>
tk                        8.6.8                ha441bb4_0  
toml                      0.10.0           py37h28b3542_0  
tox                       3.14.1                   pypi_0    pypi
tqdm                      4.36.1                     py_0  
twine                     2.0.0                    pypi_0    pypi
typed-ast                 1.4.0                    pypi_0    pypi
unify                     0.5                      pypi_0    pypi
untokenize                0.1.1                    pypi_0    pypi
urllib3                   1.24.2                   py37_0  
virtualenv                16.7.7                   pypi_0    pypi
wcwidth                   0.1.8                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.33.6                   py37_0  
xlsxwriter                1.2.2                    pypi_0    pypi
xopen                     0.8.4                    py37_0    conda-forge
xsv                       0.13.0                        0    conda-forge
xz                        5.2.4                h1de35cc_4  
yaml                      0.1.7                hc338f04_2  
zipp                      0.6.0                    pypi_0    pypi
zlib                      1.2.11               h1de35cc_3  ```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by peterjc** [comment]
Reproduced on 64-bit Linux too.

**Comment by pkgw** [comment]
This won't work unless you the have Gtk+ 3 library installed in your conda environment, and conda-forge doesn't offer packages of it — the `pygobject` package offers the framework for importing Python bindings of libraries like Gtk, but you still have to actually install each library for the bindings to be available.

So, I think the real bug here is that we don't provide Gtk 3 — we only have Gtk 2, which doesn't use the gobject-introspection framework. I'm going to close this because I don't think this is a problem with this package, but feel free to reopen if I've misunderstood.

**Comment by peterjc** [comment]
Thanks, so the missing dependency is the entire Gtk+ 3 library, which is not currently on conda-forge. Not an easy fix then.

**Comment by pkgw** [comment]
Yes. I have made a `gtk3` package as part of my [pkgw-forge](https://github.com/pkgw/conda-recipes) suite of packages, but these are not well supported and not frequently updated, so you should consider their availability as "best effort without much effort" only.

**Comment by spcogg** [comment]
Spent hours trying to follow the official [pygobject docs ](https://pygobject.readthedocs.io/en/latest/getting_started.html) and trying to figure out how to get it to work with conda. For us normal conda users that just need some version of Gtk3, Your package channel needs to have much more publicity

**Comment by pkgw** [comment]
In a total coincidence (as far as I know), gtk3 [just got added to conda-forge](http://anaconda.org/conda-forge/gtk3), so the packages in my channel should be regarded as superseded. Huzzah!

**Comment by peterjc** [comment]
Good news - so in theory this issue can be reopened and resolved within conda-forge using the new gtk3 packages as another dependency?

**Comment by pkgw** [comment]
@peterjc In my opinion we shouldn't to do that — `gtk3` is a very heavyweight dependency, and people will sometimes want to use `pygobject` to gain access to GLib-based packages other than `gtk3`. Making `gtk3` a full dependency would pull it in, and all of its dependencies, unconditionally for everyone.

That being said, people often get tripped up by the issue that spawned this thread, and it would be good to prevent the problem or at least give people very clear instructions about how to fix it. At the moment, the best idea I'm coming up with would be to patch the error message to advise installing the appropriate conda-forge package — definitely a hack, but hopefully helpful?

**Comment by peterjc** [comment]
If "conda install gtk3 pygobject" works (must manually include the gtk3 dependency), then that is a much better situation than before - and your suggestions makes a lot of sense.

In fact, asking pygobject to tweak the exception seems reasonable to me. e.g.

``ValueError: Namespace Gtk not available. Is gtk3 installed?``

**Comment by ranchester2** [comment]
I have done the workaround in the comment. and it seems to work.

But Gtk.Template doesn't work

`AttributeError: 'gi.repository.Gtk' object has no attribute 'Template'`

**Comment by peterjc** [comment]
@ranchester2 your issue sounds different - worth opening a separate issue but I'm not immediately sure where.
